### ISSUE TITLE
Crash in try_gluon

### ISSUE THREAD

**Issue by Marwes** [Marwes/gluon#171]
`try_gluon` crashed overnight and unfortunately I made an error when enabling the logging so this is all relevant logging for now. Presumably it has to do with the garbage collector but hopefully it occurs again so I can get some more information.

```
hread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.2.0/src/thread.rs:1082
error: Process didn't exit successfully: `target/release/main` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by brendanzab** [comment]
Can we run gluon in a subthread, and catch panics at the boundary?

**Comment by Marwes** [comment]
panics are already caught by iron so I don't think that is necessary.

**Comment by Marwes** [comment]
There might be two errors at play here, one that causes the panics and one that causes the segfaults.

**Comment by Marwes** [comment]
https://gist.github.com/Marwes/825b1ff9f5484f1ccdfb0eba9f828286

Looks like the process ran out of memory, it might be the stack consuming all memory actually. I may have missed adding limits for that.

**Comment by Marwes** [comment]
```
let factorial n : Int -> Int =
    n * factorial (n - 1)

factorial 10
```

From /r/rust https://www.reddit.com/r/rust/comments/552l6s/gluon_02_released_now_with_rowpolymorphic_records/d881pea
